const API_BASE = 'https://pixabay.com/api/music/';

interface SoundHit {
    duration: number;
    previewURL: string;
}

/**
 * Searches the Pixabay API for a suitable ambient sound track.
 * @param query The search query generated by the AI.
 * @param apiKey The user's Pixabay API key.
 * @returns A URL to an audio file or null if not found.
 */
export async function searchSounds(query: string, apiKey: string): Promise<string | null> {
    const params = new URLSearchParams({
        key: apiKey,
        q: query,
        per_page: '15',
        category: 'ambient', // Switched to a valid and more appropriate category
    });

    try {
        const response = await fetch(`${API_BASE}?${params.toString()}`);
        if (!response.ok) {
            console.error('Pixabay API request failed:', response.statusText);
            return null;
        }

        const data = await response.json();
        
        // Filter for longer tracks (> 60s) to use as ambient loops
        const longTracks: SoundHit[] = data.hits.filter((hit: SoundHit) => hit.duration > 60);

        if (longTracks.length > 0) {
            // Pick a random one from the filtered list
            const randomIndex = Math.floor(Math.random() * longTracks.length);
            return longTracks[randomIndex].previewURL;
        } else if (data.hits.length > 0) {
            // If no long tracks, fallback to a random shorter one
            const randomIndex = Math.floor(Math.random() * data.hits.length);
            return data.hits[randomIndex].previewURL;
        }

        return null; // No sounds found
    } catch (error) {
        console.error('Error searching for sounds on Pixabay:', error);
        return null;
    }
}